### ISSUE TITLE
Are we ndarray 0.15 ready yet?

### ISSUE THREAD

**Issue by relf** [rust-ml/linfa#124]
I open this issue to keep track of stuff required to bump to `ndarray 0.15`. From #110 we get the following list:

- [x] approx = 0.4
- [x] argmin = 0.4.6
- [x] ndarray-csv = 0.5.1
- [x] ndarray-linalg = 0.14.0
- [x] ndarray-npy = 0.8
- [x] ndarray-rand = 0.14
- [x] ndarray-stats = 0.5
- [x] num-traits = 0.2
- [x] rand = 0.8
- [x] rand-isaac = 0.3
- [x] sprs

**Comment by quietlychris** [comment]
I just submitted a pull request to `ndarray-csv` updating it to use `0.15`, and will add an update if it gets merged/a new version is posted to crates.io

**Comment by quietlychris** [comment]
@relf I believe that we should be all set with `ndarray-csv` now--`0.15` should be supported with `ndarray-csv = "0.5.1"`

**Comment by YuhanLiin** [comment]
Are we waiting for `argmin`, `ndarray-linalg`, and `sprs` to include `ndarray` 0.15 in their dependencies before bumping?

**Comment by relf** [comment]
Well... I guess it was the plan, thinking that linfa's dependencies would upgrade rapidly. Do you suggest we could bump some of linfa's subcrates?

**Comment by relf** [comment]
Yep, we agree. Btw it seems dificult to mix different versions of `ndarray` anyway (when it occurs by mistake it ends up with compilation errors).

**Comment by bytesnake** [comment]
both `sprs` and `ndarray-linalg` are already using `ndarray = 0.15` in their git tree, but they are not yet published to `crates.io`. I also created an issue at `argmin` side https://github.com/argmin-rs/argmin/issues/123

**Comment by relf** [comment]
`ndarray-linalg` and `argmin` on `ndarray = 0.15` are published, one to go...

**Comment by bytesnake** [comment]
I would like to update all dependencies to `ndarray = 0.15` before publishing a new linfa version

**Comment by mulimoen** [comment]
`sprs` 0.11.0 was published right now, and uses `ndarray = 1.15`

**Comment by relf** [comment]
Closed by #156
