### ISSUE TITLE
Bindings for Ruby and newer Roadmap

### ISSUE THREAD

**Issue by chandranshu12** [rust-ml/linfa#132]
I happened to land here through a post on Hacker News and this looks very interesting. Unfortunately, the blog post was from Decemeber 2019 and the link was only posted there recently. I see that most of the original roadmap has been already implemented. Kudos for that!

I have two questions though:
1. Are there any plans to add bindings for Ruby or any other programming language at the moment? I ask this since Ruby has been my primary programming language for 12+ years and I still find it lacking in ML support. This project may just fill the gap.
2. Is the roadmap going to be extended any time soon to include any additional algorithms or variations? Also, is the [scikit-learn](https://scikit-learn.org/stable/) compatibility an intermediate or final goal of the project?

Thanks again for all the awesome work!

**Comment by bytesnake** [comment]
>     1. Are there any plans to add bindings for Ruby or any other programming language at the moment? I ask this since Ruby has been my primary programming language for 12+ years and I still find it lacking in ML support. This project may just fill the gap.
> 

yes there are, but we don't have the capacity right now. I'm happy to accept any PR which tries to add bindings for a language though

>     2. Is the roadmap going to be extended any time soon to include any additional algorithms or variations? Also, is the [scikit-learn](https://scikit-learn.org/stable/) compatibility an intermediate or final goal of the project?
> 
> 

the roadmap is non-exhaustive and updated constantly. If you are interested in implementing something new, just add a comment below it and I will take it into the list. Compatibility with scikit-learn is not a goal as the language is quite different and we don't need to be backward compatible at this point. Feature-wise we are seeking to come on-par with scikit-learn of course.

> Thanks again for all the awesome work!

Let me know if you need anything or find a bug :)

**Comment by chandranshu12** [comment]
Thanks for your reply. I'll definitely be interested in adding language bindings for ruby and may be Node.js.
