### ISSUE TITLE
Enable features in CI

### ISSUE THREAD

**Issue by YuhanLiin** [rust-ml/linfa#135]
Right now CI doesn't enable any Cargo features. I suggest that we run a separate `cargo check` on the algorithm crates with all non-conflicting features enabled, to avoid bugs like #128. At the very least we should check the crates with `serde` enabled.

**Comment by bytesnake** [comment]
yeah I tried to add `serde` support to the action but there is no way to enable a feature for all sub-crates at the moment

**Comment by YuhanLiin** [comment]
Can we add a `serde` feature to all crates/sub-crates and then have a new CI step that runs `cargo check` with the `--features serde` flag?

**Comment by bytesnake** [comment]
I don't think that works, you'd have to specify the target crate and wildcards like `--features */serde` are not implemented

**Comment by YuhanLiin** [comment]
Can't we put `--features serde` in the args? If the CI command is running for every crate then there should be no need to specify target crate as long as every crate has the `serde` feature, which we may not want.

**Comment by YuhanLiin** [comment]
Apparently you can specify features for specific crates when you call "cargo check" on a workspace. See https://doc.rust-lang.org/cargo/commands/cargo-check.html#feature-selection for more details.

**Comment by bytesnake** [comment]
I would propose adding a `linfa/serde` feature flag and use it in downstream crates to solve the base error issue
