### ISSUE TITLE
Serializing CountVectorizer and Models

### ISSUE THREAD

**Issue by Vikramardham** [rust-ml/linfa#139]
Hello,

Is there a way to serialize the preprocessing steps like CountVectorizer?

Any help would be greatly appreciated!

**Comment by YuhanLiin** [comment]
`linfa-preprocessing` currently has no Serde support, but I don't see any reason why it can't be added. If you open a PR adding Serde support under a feature flag (similar to other Linfa crates) then I'd be happy to look over it.

**Comment by Vikramardham** [comment]
Added the serde support in a patched version. Seems to work. Will push after testing. Thanks!

**Comment by YuhanLiin** [comment]
Resolved by #292
