### ISSUE TITLE
Replace the term "hyperparam" with "param"

### ISSUE THREAD

**Issue by YuhanLiin** [rust-ml/linfa#151]
This applies to type names, docs, as well as comments. The term "param" is shorter and more general than "hyperparam", and "hyperparam" is also a bit of a misnomer, since most of what we call "hyperparams" inside Linfa aren't actually hyperparameters. See [here](https://github.com/rust-ml/linfa/pull/142#issuecomment-874438697) for discussion on this.

**Comment by YuhanLiin** [comment]
@bytesnake Should we rename instances of "hyperparam" in the docs/comments or just close this issue?

**Comment by bytesnake** [comment]
Just removed `Hyper` from struct definitions in that PR, otherwise I'm still using it in most cases to distinguish them from learnable parameters.
