### ISSUE TITLE
Feature for onnx

### ISSUE THREAD

**Issue by franklucky001** [rust-ml/linfa#167]
Is there have any plans to support onnx?
sklearn can convert model to onnx format by [https://github.com/onnx/sklearn-onnx.](url)
I hope Linfa will support onnx in the future

**Comment by bytesnake** [comment]
If you want to use ONNX models, please use https://docs.rs/onnxruntime/0.0.14/onnxruntime/. We are just consumer and one layer above, so if you want to create an algorithm which uses some ONNX model underneath, don't hesitate to utilize such crates.
