### ISSUE TITLE
SVM clonable

### ISSUE THREAD

**Issue by glitch4347** [rust-ml/linfa#174]
Hi. Thank you for the lib. 
I propose to make https://github.com/rust-ml/linfa/blob/master/algorithms/linfa-svm/src/lib.rs#L117 to be clonable.

Motivation is simple: I want to train model and then move it to another thread,

**Comment by YuhanLiin** [comment]
Can't you move it without cloning?

**Comment by glitch4347** [comment]
@YuhanLiin I would use SVM in multiple threads on sifferent subsets simultaneously and I would avoid using `.lock()`.

**Comment by YuhanLiin** [comment]
What are you calling on the SVM? The fitting methods don't take `&mut` so you should be able to share the SVM across multiple threads without cloning.

**Comment by YuhanLiin** [comment]
@glitch4347 Are you still having the issue? If not then I'll be closing this.
