### ISSUE TITLE
[Question ] do we have something for reinforcement learning?

### ISSUE THREAD

**Issue by trsh** [rust-ml/linfa#175]
I can't find anything on RL.

**Comment by relf** [comment]
Short answer: no. :wink: 

Longer answer: as linfa aims at having the same scope as scikit-learn, I think [it excludes RL for the same reasons](https://scikit-learn.org/stable/faq.html#why-is-there-no-support-for-deep-or-reinforcement-learning-will-there-be-support-for-deep-or-reinforcement-learning-in-scikit-learn).

**Comment by bytesnake** [comment]
Hi @trsh,
as @relf said, the scope of this crate is similar to scikit-learn. Rust's ML ecosystem is still very young, but perhaps you can find some pointers in the are-we-learning-yet section for RL https://www.arewelearningyet.com/reinforcement-learning/

Thanks for your interest!
