### ISSUE TITLE
MultiTaskLasso, GroupLasso and Lasso-like models

### ISSUE THREAD

**Issue by PABannier** [rust-ml/linfa#191]
I can certainly implement MultiTaskLasso, as well as GroupLasso, in the ElasticNet package.
Would you consider a valuable addition to the crate?

**Comment by YuhanLiin** [comment]
You're referring to something like [multi-task ElasticNet](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.MultiTaskElasticNet.html) right? Extending existing algorithms is certainly welcome.

**Comment by PABannier** [comment]
#194
