### ISSUE TITLE
Split `AsTarget` and `AsTargetMut` into 1D and 2D traits

### ISSUE THREAD

**Issue by YuhanLiin** [rust-ml/linfa#195]
`AsTarget` and `AsTargetMut` support return 1D and 2D targets. However, most uses of the traits require either 1D targets or 2D targets, but never both. Also, some impls don't support 1D targets, so `try_single_target()` has to return a `Result` to handle that case. I propose that we split `AsTarget` into `AsSingleTarget` and `AsMultiTarget` (same with `AsTargetMut`) and implement them on `ArrayView1` and `ArrayView2` respectively. Trait bounds will be changed to use one or the other. What do you think @bytesnake ?

**Comment by PABannier** [comment]
I think that would be of great help! I can work on it. Actually without that kind of tweak, I'm stuck with #194 .

**Comment by YuhanLiin** [comment]
Closed by #206
