### ISSUE TITLE
Support sparse vector in linear nearest neighbor

### ISSUE THREAD

**Issue by TristanCacqueray** [rust-ml/linfa#200]
Similar to #192 , would it be feasible to use sprs vector when creating (batch argument) and doing k_nearest (point argument)? In scikit-learn, the NearestNeighbor class default to brute algorithm when the data is sparse.

**Comment by YuhanLiin** [comment]
From what I read [here](https://scikit-learn.org/stable/modules/neighbors.html), the concept of sparsity used for the data is different from the way we use the term "sparse" to describe sparse matrices, as quoted here:
> Sparsity refers to the degree to which the data fills the parameter space (this is to be distinguished from the concept as used in “sparse” matrices. The data matrix may have no zero entries, but the structure can still be “sparse” in this sense).
>
I'm not sure how exactly they define "sparse", but I don't think it has anything to do with `sprs`.

**Comment by YuhanLiin** [comment]
OK so I looked at `scipy`'s source code and they do use the same definition of "sparse" as `sprs`. In fact they only allow brute force algorithm when the input is sparse. The docs were just confusing. Currently we don't support sparse matrices for `NearestNeighbours`, so we can definitely add support for that but only allow the brute force algorithm. If we want to use the existing `NearestNeighbours` traits we may need to make them more flexible, since they only work on `Array`.

**Comment by TristanCacqueray** [comment]
Thank you for looking into that. I guess this is an edge case, and perhaps this should not be added to `linfa-nn`. It seems like scikit-learn is using a pairwise_distance implementation in that case (see https://github.com/scikit-learn/scikit-learn/blob/7e1e6d09bcc2eaeba98f7e737aac2ac782f0e5f1/sklearn/neighbors/_base.py#L739-L761). 

Though this is useful for the problem I'm trying to solve, where I basically need a function that returns the smallest cosine distance between a sparse vector, and a list of sparse vector.

**Comment by YuhanLiin** [comment]
I'm not sure about adding cosine distance to `linfa-nn` because it might not be compatible with tree-based NN algorithms. In the case of sparse matrices, it only works with brute force algorithms, so I agree that it doesn't really fit in `linfa-nn`. Easiest way would be to implement the brute force routine yourself, since the logic is really simple.

**Comment by TristanCacqueray** [comment]
Alright, I'll implement the routine in my lib, and I would be happy to contribute it back if it can be useful to `linfa`.

Thanks again for the feedback and for developing rust-ml :)

**Comment by TristanCacqueray** [comment]
For the record, here is what I got working for my [logreduce index](https://github.com/logreduce/logreduce-rust) use case: 

```rust
use fxhash::hash32;
use itertools::Itertools;
use sprs::*;

pub type F = f32;
pub type SparseVec = CsVecBase<Vec<usize>, Vec<F>, F>;
pub type FeaturesMatrix = CsMatBase<F, usize, Vec<usize>, Vec<usize>, Vec<F>>;
const SIZE: usize = 260000;

/// Create a normalized matrix
pub fn create_mat(vectors: &[SparseVec]) -> FeaturesMatrix {
    let mut mat = TriMat::new((vectors.len(), SIZE));
    for (row, vector) in vectors.iter().enumerate() {
        let l2_norm = vector.l2_norm();
        for (col, val) in vector.iter() {
            mat.add_triplet(row, col, *val / l2_norm);
        }
    }
    mat.to_csr()
}

/// Compute the smallest cosine distance between two normalized matrix. The rhs must be transposed.
pub fn search(baselines: &FeaturesMatrix, targets: &FeaturesMatrix) -> Vec<F> {
    let mut distances_mat = baselines * targets;
    distances_mat.transpose_mut();
    distances_mat
        .to_dense()
        .outer_iter()
        .map(|row| row.iter().fold(1.0, |acc: F, v| acc.min(1.0 - v)))
        .collect::<Vec<_>>()
}

/// Word based hashing vectorizer
pub fn vectorize(line: &str) -> SparseVec {
    let (keys, values) = line
        .split(' ')
        .map(|word| {
            let hash = hash32(word);
            // alternate sign
            let sign = if hash >= 2147483648 { 1.0 } else { -1.0 };
            ((hash as usize) % SIZE, sign)
        })
        .sorted_by(|a, b| Ord::cmp(&a.0, &b.0))
        .dedup_by(|a, b| a.0 == b.0)
        .unzip();
    CsVec::new(SIZE, keys, values)
}
```
