### ISSUE TITLE
Moving ownership to the ML Working Group

### ISSUE THREAD

**Issue by LukeMathWalker** [rust-ml/linfa#21]
Following my message to the [ML WG](https://github.com/rust-ml/wg) [Zulip chat](https://rust-ml.zulipchat.com/):

> As some of you might have noticed, my activity in the ML corner of the Rust ecosystem has quite diminished over the last few months.
>
> Due to what amounts to a career change (ML -> Software Engineer) I have been focusing more on the web/networking ecosystem and I have found it more and more time-consuming to context-switch at the end of the day to work on ML topics.
Motivation plays a role there too, being myself less engaged in the future evolution of the ecosystem.
>
> I'd thus be more than open to move ownership of linfa over to the WG or to a subset of volunteers with an interest in moving the project forward.

I moved the ownership of `linfa` to `rust-ml`, which is going to be a better steward going forward, with surely more helping hands to dedicate to the project.

My sincerest apologies to @paulkoerbitz, @mossbanay and @bytesnake. I left your PRs unanswered for a long time, but I really couldn't manage to juggle the number of projects I have been working on  during the last few months.

:rocket:

**Comment by bytesnake** [comment]
Hey,
honestly I completely forgot about my PR here :laughing: I think that this is the right decision, and should avoid more slowdown in the decision making. In my opinion an agglomerative crate of traditional machine learning algorithms is an important part in the `rust-ml` group and your contribution is therefore very welcome. I'm currently busy with my master thesis, but planing to spend some time on fast support vector machines in the next month. The infrastructure is still very immature at the moment, but `linfa` should help us identify important algorithms. (like fast partial eigenvalue decomposition for spectral clustering or convex optimization for SVM) Wish you best of luck at your new job, hope you will continue the scientific computing blog series one day :)

**Comment by mossbanay** [comment]
No stress, as @bytesnake said above I enjoyed your blog posts and tried to give back a bit where possible. If there's a better place for the project to be organized that might give it a better chance to grow then that's fine with me.
There's probably a lot of room for improvement in my PR, if I find some time I may have a go at rewriting parts of it too. Looking forward to the future of ML in the rust ecosystem.

**Comment by paulkoerbitz** [comment]
Hey @LukeMathWalker! Just saw this today - thanks for taking the step. I've certainly have a few unmaintained projects under my belt, so I think we all know how it is ;). Looking forward to this project becoming more active again!

**Comment by paulkoerbitz** [comment]
@LukeMathWalker thank you for starting linfa and transferring ownership! We're looking forward to taking this crate forward and would love if you're availability allows you to play a more active role again!

I'm closing this issue for now as the transfer has been completed.
