### ISSUE TITLE
DBScan with custom distance function?

### ISSUE THREAD

**Issue by literadix** [rust-ml/linfa#224]
Is it possible to provide a custom distance function to dbscan? Could you provide an example if it is possible or share ideas how to implement?

Kindly regards,

Maciej

**Comment by YuhanLiin** [comment]
```rust
use linfa_clustering::Dbscan;
use linfa_nn::{Distance, CommonNearestNeighbour};

// This allows the CustomDist type to be used as a distance function
impl Distance<f64> for CustomDist {
  ...
}

fn main() {
  ...
  let params = Dbscan::params_with(min_points, CustomDist, CommonNearestNeighbour::KdTree);
  let cluster_memberships = params.tolerance(tol).transform(dataset).unwrap();
}
```

**Comment by literadix** [comment]
@YuhanLiin Thank you very much. Could you give my a more precise example how to code the distance function? How do I write such a function if I have a data set with rows like this:

latitude<f64>, longitude<f64>, speed<f64>, bearing<f64>

**Comment by literadix** [comment]
I see there are some examples in the core library:

https://github.com/rust-ml/linfa/blob/master/algorithms/linfa-nn/src/distance.rs
