### ISSUE TITLE
Broken link in linfa-logistic documentation

### ISSUE THREAD

**Issue by quietlychris** [rust-ml/linfa#245]
I was just scrolling through a part of of the `linfa-logistic`, and came across a documentation linking error for the link to https://docs.rs/linfa-logistic/latest/linfa_logistic/struct.LogisticRegression.html from the crate's index page. It might make sense to add a CI check to run a linkchecker over the `index.html` files created by `cargo doc` in each of the sub-crates to help keep an eye on this. 

One option for this could be the [`lychee`](https://github.com/lycheeverse/lychee) crate, which seems to have a number of installation options (although `cargo install` probably isn't a good option, since it has something like 400 deps to build from source).

**Comment by gkobeaga** [comment]
Perhaps `#![deny(rustdoc::broken_intra_doc_links)]` can be set for the crates?

https://doc.rust-lang.org/rustdoc/lints.html?highlight=link#broken_intra_doc_links

**Comment by gkobeaga** [comment]
Could it be closed?

**Comment by YuhanLiin** [comment]
Yep
