### ISSUE TITLE
Add Precommit Hook

### ISSUE THREAD

**Issue by oojo12** [rust-ml/linfa#258]
Part of the CI checks for code quality with `cargo fmt` and `cargo clippy` It may be nice for developers if we had a precommit hook to automatically perform these tasks.

**pre-commit actions**
- [ ] linting with cargo clippy
- [ ] formatting with cargo fmt

**Comment by oojo12** [comment]
Seems possible though I haven't tested it. See excerpt taken from [pre-commit](https://pre-commit.com/), there is also no mention of needing GHE.  

"""
Run pre-commit install to install pre-commit into your git hooks. pre-commit will now run on every commit. Every time you clone a project using pre-commit running pre-commit install should always be the first thing you do.

If you want to manually run all pre-commit hooks on a repository, run pre-commit run --all-files. To run individual hooks use pre-commit run <hook_id>.

The first time pre-commit runs on a file it will automatically download, install, and run the hook. Note that running a hook for the first time may be slow. For example: If the machine does not have node installed, pre-commit will download and build a copy of node.
"""

Also, [git documentation](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) on pre-commit hooks.

If desirable I can validate this and make a PR if it works.

**Comment by YuhanLiin** [comment]
IMO having CI to validate this stuff is sufficient on the server. If you want to use hooks for this then you can install it locally.
