### ISSUE TITLE
Tabular Data Generating Func for Benchmarks?

### ISSUE THREAD

**Issue by oojo12** [rust-ml/linfa#259]
Would it be helpful for benchmarking to have a tabular data generating function?

For completeness this is what I am thinking can be added to the datasets module:

```
struct DataSpecs {
    rows: usize,
    cols: usize,
    targets: usize,
    feat_distribution: Uniform<f32>,
    target_distribution: Uniform<i8>,
}

impl DataSpecs {
    fn new(
            rows: usize,
            cols: usize,
            targets: usize,
            feat_distribution: Uniform<f32>,
            target_distribution: Uniform<i8>,
        ) -> DataSpecs {
        
            DataSpecs {
                rows,
                cols,
                targets,
                feat_distribution,
                target_distribution
            }
    }
}
```

and something like this be added to the generate.rs

```
fn make_dataset(data_specs: DataSpecs) -> Dataset<f32, i8> {
    let features = Array::random((data_specs.rows, data_specs.cols), data_specs.feat_distribution);
    let targets = Array::random((data_specs.rows, data_specs.targets), data_specs.target_distribution);

    Dataset::new(features, targets)
```

where this would be an example usage

```
fn main() {
    let data_specs = DataSpecs::new(10, 10, 1, Uniform::new(-5., 5.), Uniform::new(0, 2));
    println!("{:#?}", data_specs);

    let data = make_dataset(data_specs);

    println!("{:#?}", data);
}
```

Alternatively, we could have the following instead of a new method implementation to instantiate the struct with keyword arguments. It might be more user friendly if this is a helpful feature for development efforts.

```
let data_specs = DataSpecs{ rows: 10, cols: 10, targets: 1, feat_distribution: Uniform::new(-5., 5.), target_distribution: Uniform::new(0, 2)};
```

**Comment by YuhanLiin** [comment]
The idea is good (we should support non-uniform distributions though). If we want to support a kwargs-like API then we should get rid of `DataSpecs::new`, since it defeats the whole purpose of kwargs. Otherwise we should get rid of `DataSpecs` and just make its fields into args for `make_dataset`.

**Comment by oojo12** [comment]
I'll do the args version as I don't feel strongly either way.
