### ISSUE TITLE
Run all Benches in Benching.yaml?

### ISSUE THREAD

**Issue by oojo12** [rust-ml/linfa#269]
Currently, we have a workflow to run benchmarks specifically for Iai benches which we are transitioning away from in favor of Criterion. Should we make the benches yaml generic and have it run all benchmarks instead with `cargo bench --all`? This way if we transition away from Criterion, we won't have to update the bench.yaml?

**Comment by YuhanLiin** [comment]
We shouldn't be running Criterion benchmarks at all in CI, since the results are highly unreliable. It also makes the CI pipeline slower for no reason. If we transition away from Criterion we'll update the CI when that happens.
