### ISSUE TITLE
linfa_datasets does not contain generate

### ISSUE THREAD

**Issue by dparks1134** [rust-ml/linfa#279]
Examples in `linfa_clustering` make use of `use linfa_datasets::generate`, but v0.6.0 of `linfa_dataset` does not contain `generate`. Is the documentation out-of-date or am I missing a way to import `generate` from `linfa_dataset`? Thanks for your help.

**Comment by YuhanLiin** [comment]
Did you activate the `generate` feature?

**Comment by dparks1134** [comment]
Is this done through the `Cargo.toml` file? The documentation for `linfa_dataset` doesn't mention `generate` best I can tell.

**Comment by YuhanLiin** [comment]
Yes in the Cargo.toml file. We need to add `generate` to the docs.

**Comment by dparks1134** [comment]
Thanks - much appreciated.
