### ISSUE TITLE
Remove version fix on anyhow crate

### ISSUE THREAD

**Issue by gilad-rosenblatt** [rust-ml/linfa#281]
In the current [crates.io release](https://crates.io/crates/linfa-clustering) (0.6.0) there is a [version fix on the `anyhow` dependency](https://github.com/rust-ml/linfa/blob/0.6.0/Cargo.toml#L48) to '<=1.0.48`. This version fix is conflicting with the `anyhow` version '1.0.65` I have for an ML project I'm working on. Since the `anyhow` version fix has since been removed in current `master`, would it be possible to cut a new release so that I can use `linfa`?

**Comment by YuhanLiin** [comment]
For the time being, you can set `anyhow = 1` to resolve the conflict, assuming you don't need any newer `anyhow` features.

**Comment by YuhanLiin** [comment]
I've done a 0.6.1 release without the `anyhow` conflict

**Comment by gilad-rosenblatt** [comment]
Thanks for the new release. Works for me.
