### ISSUE TITLE
I am trying to get Linfa to work with apple M2 accelerate:

### ISSUE THREAD

**Issue by ludiusvox** [rust-ml/linfa#287]
I was able to get the SVM demo working on apple M2 chip, however I want to do linear regressions with the BLAS-LAPACK/OPENBLAS libraries I can install through brew but I am having difficulty linking through rust into the demo code just to run regressions on a dataset.  Apple has accelerate code build in their own libraries for hardware accelleration instead of Intel MKL, is there any plan on supporing MacOS accelerate?

Thanks,
Worst comes to Worst I can just operate on github codespaces a remote terminal and run on an x64 system.

**Comment by YuhanLiin** [comment]
Can you try `intel-mkl-static`? That might work on Mac. If not, then you'll need to use the non-accelerated algorithm.

**Comment by ludiusvox** [comment]
I will try
