### ISSUE TITLE
Clarify versioning of linfa and linfa sub-crates

### ISSUE THREAD

**Issue by paulkoerbitz** [rust-ml/linfa#29]
How will versioning of linfa and its sub-crates work? Currently the version of linfa on crates.io is 0.1.2 (although in Cargo.toml its still 0.1.1) and linfa-clustering is released on crates.io as 0.1.0 (consistent with Cargo.toml).

Some questions that come to mind:
1.  Should all sub-crates (linfa-clustering, etc.) have the same version as the main version (my guess is not)?
2. Do we have to release each version of the main linfa and each of the sub-crates by hand?
3. Does the main linfa crate get a release every time any of its sub-crates gets a release?

**Comment by bytesnake** [comment]
I would publish a new patch version for every update we have concerning an algorithm (and increment the version number only in the base and patched sub-crate), and a minor version every time a new algorithm is added. A `1.0` release is due when the major parts of algorithms in #7 are implemented and we have a consistent API.

1. The major/minor version should be the same, patch version can be different
2. Yes we have to unfortunately, see https://github.com/rust-lang/cargo/issues/1169
3. Not for patches, only when there is a new algorithm
