### ISSUE TITLE
linfa-clustering depends on partitions 0.2.4, which throws future-incompatibilities warnings

### ISSUE THREAD

**Issue by eric-seppanen** [rust-ml/linfa#295]
When testing rust 1.68.0, I see the following warning:
```
warning: the following packages contain code that will be rejected by a future version of Rust: partitions v0.2.4
```
That crate is a dependency of `linfa-clustering`.

I would guess that the `partitions` crate is no longer maintained. It hasn't been touched in 5 years and there hasn't been any response to the [issue](https://github.com/DDOtten/partitions/issues/2).

**Comment by YuhanLiin** [comment]
Resolved by #298
