### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by paulkoerbitz** [rust-ml/linfa#30]
There are some broken links and other items that need update in the readme before we reach out to a wider audience:

- Links to chat (I think we want this to be the rust-ml zulip channel for now)
- Links to build and coverage info (part of fixing up the CI builds)
- Current state section: Update this to the current state and make it a bit more timeless

Some things which would also be at least nice to haves:
- Collaboration guidelines

**Comment by paulkoerbitz** [comment]
@bytesnake @quietlychris happy to take a first stab at this, but interested in your input.

**Comment by bytesnake** [comment]
Yes please go ahead, I mean I really like the beginning and end, but the middle part is outdated.

**Comment by quietlychris** [comment]
All of those points sound great. I'm not sure I have time today, but will definitely be happy to provide input/add/edit this weekend

**Comment by bytesnake** [comment]
* add a note how to use the system openblas library [[1]](https://github.com/blas-lapack-rs/openblas-src)

**Comment by quietlychris** [comment]
I'd just like to +1 about adding a note for using the system openblas library. Compiling the `openblas-src` dependency is really heavyweight, and trying to compile it without a fairly powerful dev machine takes a while. For someone coming over from something like the Numpy ecosystem, that might be a fairly big paint point, so reducing that or at least explicitly noting it should definitely be something that gets done.

**Comment by bytesnake** [comment]
added note how to select the BLAS/LAPACK backend in https://github.com/rust-ml/linfa/commit/7296c9ec4925f9c7d87c15a77be329ed3e4a38a0
