### ISSUE TITLE
Fix CI build, make CI run automatically

### ISSUE THREAD

**Issue by paulkoerbitz** [rust-ml/linfa#31]
Make the CI build run again.

Discussion: Should we enable Clippy for the project?

**Comment by bytesnake** [comment]
Glanced at travis in `ndarray` and they [run](https://github.com/rust-ndarray/ndarray/blob/master/.travis.yml) a test [script](https://github.com/rust-ndarray/ndarray/blob/master/scripts/all-tests.sh) for `1.37.0`, `stable`, `beta` and `nightly`. I'm very much in favor of Clippy

**Comment by quietlychris** [comment]
I'm not sure how I feel about clippy for scientific programming. I know that it generally recommends more "idiomatic" code, but I've seen several suggestions from it, particularly around iterators, that take code that is perhaps slightly less technically idiomatic (but much easier to interpret and maintain for humans) and turn it into an absolute mess. Other times, of course, the suggestions are great. 

If we do use clippy, I might suggest it not being using the `clippy::all` [option](https://github.com/rust-lang/rust-clippy), and instead choose a subset of them in the CI like just `clippy::correctness` and `clippy::complexity`, and then recommending that suggestions or changes from other lints be made in the Submission Guidelines in the README.

**Comment by paulkoerbitz** [comment]
Great comments - thank you. 

I've left clippy for a later PR - we can look into the changes then and (partially) have a final decision then.
