### ISSUE TITLE
Serialize a trained model to disk?

### ISSUE THREAD

**Issue by zachcp** [rust-ml/linfa#316]
Hi Team-Linfa, 

This is a wonderful effort and I am kicking the tires. One thing I would like to be able to do is to train a model and save the model to disk in order to reload/reuse it later. However, my initial attempts have all hit Serialization issues (see below).  The source code seems to have serialization (and `derive`) enabled for `DecisionTree` so I am not sure how to resolve this and I would appreciate any pointers. 

thanks!
zach cp

```rust
// to https://github.com/rust-ml/linfa/blob/master/algorithms/linfa-trees/examples/decision_tree.rs
// add these deps
use bincode::{deserialize, serialize, Options};
use ::serde_json;


// try serde_json
println!("{}", serde_json::to_string(&entropy_model).unwrap());
//  ^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `DecisionTree<f64, usize>`


// try bincode
println!("{:?}",  bincode::serialize(&entropy_model).unwrap());
//^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `DecisionTree<f64, usize>`

```

**Comment by zachcp** [comment]
So for `serde` to work I needed to invoke cargo differently:

```rust
// to https://github.com/rust-ml/linfa/blob/master/algorithms/linfa-trees/examples/decision_tree.rs
// add these deps
use bincode;
use std::fs::File;

// updated lines
let _encoded: Vec<u8> = bincode::serialize(&entropy_model).unwrap();
let mut file = File::create("my_data.bin").unwrap();
bincode::serialize_into(&mut file, &_encoded).unwrap();
```


```sh
cargo run --release --example decision_tree --features serde
```

**Comment by YuhanLiin** [comment]
The key here is `--features serde`. You need to enable the `serde` feature on `linfa-trees` to enable the Serde support.

**Comment by coolstudio1678** [comment]
I serialize the  trained trees model，when I deserialized, what type should I type？ 
``` let ser = rmp_serde::to_vec(&model).unwrap(); let deser = rmp_serde::from_slice(&ser).unwrap(); ``` 
abouve code show error : type must be known at this point.
