### ISSUE TITLE
Undefined reference to `LAPACKE_dgetrs' - Linux Mint 20

### ISSUE THREAD

**Issue by moriartydev** [rust-ml/linfa#33]
`  = note: /usr/bin/ld: /home/m0riarty_d3v/WebstormProjects/linfa/target/debug/deps/libndarray_linalg-ab5e3b1dfd453661.rlib(ndarray_linalg-ab5e3b1dfd453661.ndarray_linalg.1huagtdm-cgu.7.rcgu.o): in function `lapacke::dgetrf':
          /home/m0riarty_d3v/.cargo/registry/src/github.com-1ecc6299db9ec823/lapacke-0.2.0/src/lib.rs:6130: undefined reference to `LAPACKE_dgetrf'
          /usr/bin/ld: /home/m0riarty_d3v/WebstormProjects/linfa/target/debug/deps/libndarray_linalg-ab5e3b1dfd453661.rlib(ndarray_linalg-ab5e3b1dfd453661.ndarray_linalg.1huagtdm-cgu.7.rcgu.o): in function `lapacke::dgetrs':
          /home/m0riarty_d3v/.cargo/registry/src/github.com-1ecc6299db9ec823/lapacke-0.2.0/src/lib.rs:6302: undefined reference to `LAPACKE_dgetrs'
          collect2: error: ld returned 1 exit status
`
Kernel: x86_64 Linux 5.4.0-26-generic

This error appear when I execute cargo run --features openblas --example diabetes (in linfa-linear folder)

**Comment by bytesnake** [comment]
mh strange, can you check whether the symbols exist in your blas library?
 * find openblas so: `find target/* -name libopenblas.so`
 * check the symbol: `nm <path> | grep LAPACKE_dgetrs`

**Comment by quietlychris** [comment]
Fwiw, I'm unable to reproduce this issue on Ubuntu 18.04 LTS.

**Comment by paulkoerbitz** [comment]
I've stumbled into something like this before when I didn't have gfortran installed when I build the dependencies. 

@moriartydev can you check if installing the gfortran package, then deleting the target/ directory in linfa/ and then re-running the command fixes this?

**Comment by moriartydev** [comment]
> I've stumbled into something like this before when I didn't have gfortran installed when I build the dependencies.
> 
> @moriartydev can you check if installing the gfortran package, then deleting the target/ directory in linfa/ and then re-running the command fixes this?

I will check now, but I remember that I installed gfortran

**Comment by moriartydev** [comment]
Changed Linux Mint to Manjaro 20.0.3 and install all dependencies from AUR - This is fix for problem, I don't know why Linux Mint is not run linfa-linear
