### ISSUE TITLE
what  is the difference between these  libarary  and  pure rust?

### ISSUE THREAD

**Issue by zheng5yu9** [rust-ml/linfa#343]
what  is the difference between these  libarary  and  pure rust?
![image](https://github.com/rust-ml/linfa/assets/20754435/c352dff2-e197-4e50-b3c0-834b082fb0f4)

**Comment by relf** [comment]
These libraries are "well-known" BLAS implementations in C and/or Fortran and can be used here, but can be tricky to build/link with depending on the system. The pure Rust BLAS subset implementation was introduced to lower the barrier of entry in linfa as it is defenitely the easiest way to compile. That said, depending on your use case you might want to choose a BLAS implementation to get better performances. See also #228
