### ISSUE TITLE
Enable code coverage with tarpaulin

### ISSUE THREAD

**Issue by paulkoerbitz** [rust-ml/linfa#35]
Code coverage was disabled when I re-enabled the CI as I had some problems to get tarpaulin to work on our project. It should be enabled again.

**Comment by bytesnake** [comment]
I tried to use tarpaulin in #59 but got a borrowing error when covering the whole workspace https://github.com/xd009642/tarpaulin/issues/463 :/

**Comment by bytesnake** [comment]
commit https://github.com/rust-ml/linfa/commit/7296c9ec4925f9c7d87c15a77be329ed3e4a38a0 enabled tarpaulin for all crates
