### ISSUE TITLE
Remove top-level kmeans example

### ISSUE THREAD

**Issue by quietlychris** [rust-ml/linfa#37]
At the moment, there's a repeat example of the k-means algorithm example: one in the `linfa-clustering` package, and one in the top-level crate `examples/` directory. 

With a limited number of algorithms, I suppose it's possible to have an example of each in the top-level crate, but I think it will be neater if examples are kept in their respective packages. 

I'm doing a review of the `-clustering` module at the moment, so would be happy to take care of this when I'm ready to submit that PR.

**Comment by bytesnake** [comment]
done in #38
