### ISSUE TITLE
Errors Building Linfa Clustering and Linfa Reduction

### ISSUE THREAD

**Issue by zicklag** [rust-ml/linfa#63]
Hey there, interesting project! I was just getting it installed and found that I couldn't compile the docs for `linfa-clustering` or `linfa-reduction` without turning off `default-features` because of this error:

```
    Updating crates.io index
error: failed to select a version for `linfa-reduction`.
    ... required by package `nasa-gallery v0.1.0 (/home/zicklag/git/zicklag/nasa-gallery)`
versions that meet the requirements `*` are: 0.2.0

the package `nasa-gallery` depends on `linfa-reduction`, with features: `openblas-src` but `linfa-reduction` does not have these features.


failed to select a version for `linfa-reduction` which could resolve this conflict
```

**Comment by bytesnake** [comment]
Hey,
we had some problems uploading the new version to crates.io because of move of ownership from the original author. We will try to fix that as soon as possible.

27.11.2020 17:03:15 Zicklag <notifications@github.com>:

**Comment by zicklag** [comment]
No problem, I was just messing around and probably won't end up actually using `linfa`. Also I just discovered that I'm pretty sure the cause is the fact that the `default` feature depends on a `dev-dependency`, which doesn't work when included from an outside crate.

**Comment by bytesnake** [comment]
uff this is blocked on https://github.com/rust-lang/cargo/issues/7915 for stable builds. I removed the features and the linalg backend is using the system openblas library now exclusively. I will ping again when we managed to transfer ownership

**Comment by bytesnake** [comment]
everything except `linfa-clustering` should be published now. Here a small example for PCA:

### Cargo.toml
```toml
[package]
#...

[dependencies]
ndarray = "0.13"
ndarray-rand = "0.11"
openblas-src = { version = "0.9", default-features = false, features = ["system"] }

linfa = "0.2.1"
linfa-reduction = "0.2.1"  
```

### src/main.rs
```rust
use ndarray::Array;
use ndarray_rand::rand_distr::Uniform;
use ndarray_rand::RandomExt;

use linfa::{Dataset, traits::Fit, traits::Predict};
use linfa_reduction::Pca;

fn main() {
    let data = Array::random((100, 10), Uniform::new(-10., 10f64));
    let dataset = Dataset::from(data.clone());

    let proj_data = Pca::params(2)
        .fit(&dataset)
        .predict(data.view());

    dbg!(&proj_data);
}
```
