### ISSUE TITLE
strange question

### ISSUE THREAD

**Issue by cymqqqq** [rust-ml/linfa#64]
why the project U wrote is named linfa?

**Comment by quietlychris** [comment]
Hello,

Per the README, "linfa" is the Italian word for the English world "sap", which is defined as the "vital circulating fluid of a plant." You can probably find more on those terms by looking them up in a dictionary/encyclopedia. 

This project was started by Luca Palmieri, who (I believe) chose this name based on the concept of having a common base machine learning library that is useful in many domains. It's not uncommon to see this kind of naming scheme for open-source projects (or, really, any kind of project), where a term in a different field (here, botany/dendrology) is used in a somewhat analogous way for describing how that project may be intended to be used.
