### ISSUE TITLE
README and dark theme

### ISSUE THREAD

**Issue by xd009642** [rust-ml/linfa#71]
Probably the least important issue ever, but can't see the right side of the ferris in the readme with github dark theme. Maybe consider either white outline, or white inner and black outline - or some zanier colours (orange inside black outline).

Screenshot of said issue

![Screenshot from 2020-12-13 18-19-22](https://user-images.githubusercontent.com/3472518/102014539-ef46f080-3d6f-11eb-907c-f376c6597b9c.png)

**Comment by bytesnake** [comment]
hadn't the effect of the new dark mode in mind. I added an outline to the logo and it's now looking a bit spooky in the dark mode :laughing:
