### ISSUE TITLE
pure rust / linear algebra libs

### ISSUE THREAD

**Issue by julama** [rust-ml/linfa#73]
I tried to compile linfa without any c lib dependencies without success yet. It seems that ndarray depends on a c lib (blas) but can be deactivated/is an option build dependency. 

Is there a way to compile linfa in pure rust?

**Comment by bytesnake** [comment]
unfortunately there is no linear algebra library available right now, which is written in pure Rust and has sufficient features to be usable. In `linfa` you can use `trees`, `svm` and `hierarchical` atm without any dependencies. 
There seem to be a bug with `ndarray`, when I'm using `ndarray::linalg::Dot` this always tries to use the CBLAS implementation, but with `std::ops::Mul` it seems to work without any dependency to CBLAS and uses `matrixmultiply` instead

**Comment by bytesnake** [comment]
I pushed commit https://github.com/rust-ml/linfa/commit/1c19f3fa87d1a141d8433e3ebbf60cf1561d240a which should ease the pain a bit, but there is not much more I can do. On the other hand if you want to cross compile to another architecture, you can use `--features openblas-static` and follow https://github.com/blas-lapack-rs/openblas-src

**Comment by julama** [comment]
Thanks for the clarification.
Can you elaborate on why e.g. [nalgebra](https://crates.io/crates/nalgebra) is not sufficient? What are the main missing features?

**Comment by bytesnake** [comment]
you're right we could use `nalgebra` as a pure Rust alternative, there are two things which prevent that atm
 * `nalgebra` is not compatible with `ndarray`
 *  hand written kernels are always faster and a lot of effort has to be put into such a library to be useful fast

**Comment by xiaohk** [comment]
[`nalgebra`](https://crates.io/crates/nalgebra) is much more actively maintained than [`ndarray-linalg`](https://github.com/rust-ndarray/ndarray-linalg) as well. The last commit for the latter was one year ago. 🤯

**Comment by YuhanLiin** [comment]
Update: Linfa can now be built without any external C dependencies such as BLAS. A pure-Rust alternative `ndarray` linalg library [linfa-linalg](https://github.com/rust-ml/linfa-linalg) has been created for this purpose.

**Comment by xiaohk** [comment]
> Update: Linfa can now be built without any external C dependencies such as BLAS. A pure-Rust alternative `ndarray` linalg library [linfa-linalg](https://github.com/rust-ml/linfa-linalg) has been created for this purpose.

Oh wow, thats amazing!! 🤩 Thank you so much!!!
